apiVersion: v1
kind: Service
metadata:
  name: drkiq
  namespace: default
  labels:
    app: drkiq
spec:
  ports:
    - name: drkiq
      port: 8000
      targetPort: drkiq
  selector:
    app: drkiq
