apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4.5
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          value: 'drkiq'
        - name: POSTGRES_PASSWORD
          value: 'dontwatch?v=kffacxfA7G4'
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        emptyDir: {}
