apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sidekiq-deployment
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: theabbas/drkiq:v8
        imagePullPolicy: "IfNotPresent"
        command: [ 'sh', '-c', 'bundle exec sidekiq -C config/sidekiq.yml' ]
        ports:
        - name: sidekiq
          containerPort: 8000
        env:
        - name: SECRET_TOKEN
          value: 'dontwatch?v=7nqcL0mjMjw'
        - name: WORKER_PROCESSES
          value: '1'
        - name: LISTEN_ON
          value: '0.0.0.0:8000'
        - name: DATABASE_URL
          value: 'postgresql://drkiq:dontwatch%3Fv%3DkffacxfA7G4@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000'
        - name: CACHE_URL
          value: 'redis://redis:6379/0'
        - name: JOB_WORKER_URL
          value: 'redis://redis:6379/0' 
        volumeMounts:
        - mountPath: /drkkiq/public
          name: sidekiq-data
      volumes:
      - name: sidekiq-data
        emptyDir: {}
